# Generated by Django 5.1.3 on 2024-12-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_companyrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrole',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile'),
        ),
    ]
