# Generated by Django 5.1.3 on 2024-12-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companyrole_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('qc', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('supervisor', models.BooleanField(default=False)),
                ('warehouse', models.BooleanField(default=False)),
                ('cutting', models.BooleanField(default=False)),
                ('packing', models.BooleanField(default=False)),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
