# Generated by Django 5.1.3 on 2024-12-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_staffpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile'),
        ),
    ]
